version: '3.8'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env  
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
